# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{preview}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["sifar"]
  s.date = %q{2011-01-14}
  s.description = %q{Make an ActiveRecord object previewable, and display the preview using existing/custom templates}
  s.email = %q{bigbeliever@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.homepage = %q{http://github.com/zerothabhishek/preview}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Add preview functionality to rails resources}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

